defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: team
    values:
      layout: person

collections:
  team:
    output: true
    layout: person

permalink: pretty
