defaults:
  - values:
      layout: default

  - scope:
      path: ''
      type: team
    values:
      layout: person

  - scope:
      path: ''
      type: posts
    values:
      layout: blost

  - scope:
      path: ''
      type: tools
    values:
      layout: tool

  - scope:
      path: ''
      type: projects
    values:
      layout: project

  - scope:
      path: ''
      type: research
    values:
      layout: research

  - scope:
      path: ''
      type: collaborate
    values:
      layout: collaborate

collections:
  tools:
    output: true
  team:
    output: true
  projects:
    output: true
  research:
    output: true
  collaborate:
    output: true

permalink: pretty
