defaults:
  - values:
      layout: default

  - scope:
      type: team
    values:
      layout: person

  - scope:
      type: posts
    values:
      layout: blost

  - scope:
      type: tools
    values:
      layout: tool
      output: true

  - scope:
      type: projects
    values:
      layout: project

  - scope:
      type: research
    values:
      layout: research

collections:
  tools:
    output: true
  team:
    output: true
  projects:
    output: true
  research:
    output: true

permalink: pretty
