- name: Open Data Certificates
  url: https://certificates.theodi.org/
  words: |
    That's one small step for [a] man, one giant leap for mankind.

    It suddenly struck me that that tiny pea, pretty and blue, was the Earth. I put up my thumb and shut one eye, and my thumb blotted out the planet Earth. I didn't feel like a giant. I felt very, very small.

    We are all connected; To each other, biologically. To the earth, chemically. To the rest of the universe atomically.

    As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore . . . and this is exploration at its greatest.

    The dreams of yesterday are the hopes of today and the reality of tomorrow.

- name: CSVLint
  url: http://csvlint.io/
  words: |
    The path of a cosmonaut is not an easy, triumphant march to glory. You have to get to know the meaning not just of joy but also of grief, before being allowed in the spacecraft cabin.

    We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard, because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone, and one which we intend to win.

    Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.

    Here men from the planet Earth first set foot upon the Moon. July 1969 AD. We came in peace for all mankind.

    Curious that we spend more time congratulating people who have succeeded than encouraging people who have not.
